### ISSUE TITLE
Erro ao fazer o Pull Request scan em Azure DevOps corporativo

### ISSUE THREAD

**Issue by decioluckow** [decioluckow/divulgit#94]
org.divulgit.remote.exception.RemoteException: 400 BAD_REQUEST
        at org.divulgit.azure.error.AzureErrorResponseHandler.handleErrorResponse(AzureErrorResponseHandler.java:29) ~[divulgit-remote-azure-0.1.0.jar!/:0.1.0]
        at org.divulgit.remote.rest.UniRestCaller.call(UniRestCaller.java:43) ~[divulgit-remote-0.1.0.jar!/:0.1.0]
        at org.divulgit.azure.pullrequest.AzurePullRequestsCaller.retrievePullRequest(AzurePullRequestsCaller.java:97) ~[divulgit-remote-azure-0.1.0.jar!/:0.1.0]
        at org.divulgit.azure.pullrequest.AzurePullRequestsCaller.retrievePullRequests(AzurePullRequestsCaller.java:44) ~[divulgit-remote-azure-0.1.0.jar!/:0.1.0]
        at org.divulgit.azure.pullrequest.AzurePullRequestService.retrievePullRequests(AzurePullRequestService.java:27) ~[divulgit-remote-azure-0.1.0.jar!/:0.1.0]
        at org.divulgit.azure.AzureCallerFacade.retrieveMergeRequests(AzureCallerFacade.java:83) ~[divulgit-remote-azure-0.1.0.jar!/:0.1.0]
        at org.divulgit.task.mergerequest.MergeRequestIdsRemoteScan.execute(MergeRequestIdsRemoteScan.java:94) ~[divulgit-task-0.1.0.jar!/:0.1.0]
        at org.divulgit.task.AbstractRemoteScan.run(AbstractRemoteScan.java:61) ~[divulgit-task-0.1.0.jar!/:0.1.0]
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.9.jar!/:5.3.9]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

**Comment by decioluckow** [comment]
Identificado que era devido a montagem da url com numero formatado (##.###).
